import {createFileRoute} from '@tanstack/react-router';
import {useEffect,useState} from 'react';
import {PageShell} from '@/components/automations/content-page';
import {pageHead} from '@/components/automations/seo';
import {StructuredData} from '@/components/automations/structured-data';
import {business,siteConfig} from '@/config/siteConfig';
import {Blueprint} from '@/components/automations/shared';
import {InquiryForm} from '@/components/automations/inquiry-form';
export const Route=createFileRoute('/book')({head:()=>pageHead('/book','Book a Free Call | CyberWorld Automations','Book a free 30-minute GoHighLevel blueprint call with Ayodele. Bring your industry, current CRM and biggest lead problem so we can discuss a clear next step.'),component:Book});
function Book(){const [ready,setReady]=useState(false);useEffect(()=>{const observer=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting)){setReady(true);observer.disconnect();}});const node=document.getElementById('calendar-embed');if(node)observer.observe(node);const receive=(event:MessageEvent)=>{if(event.origin!=='https://calendly.com' || event.source!==document.querySelector<HTMLIFrameElement>('#calendar-embed iframe')?.contentWindow)return;if(event.data?.event==='calendly.event_scheduled'){sessionStorage.setItem('cw-booked','yes');window.location.assign('/booking-confirmation');}};window.addEventListener('message',receive);return()=>{observer.disconnect();window.removeEventListener('message',receive);};},[]);return <PageShell title="Book a call"><StructuredData path="/book" title="Book a call"/><h1>Book a free 30-minute call</h1><p className="answer-first">You talk to Ayodele. We look at your process and decide what belongs in your automation blueprint.</p>{siteConfig.founderPhoto&&<img className="booking-photo" src={siteConfig.founderPhoto} width={180} height={180} alt="Ayodele Ezekiel, Founder at CyberWorld Automations"/>}<h2>What to prepare</h2><ul className="prepare-list"><li>Your industry and the services you offer</li><li>Your current CRM, spreadsheet or lead inbox</li><li>The biggest problem in your lead follow-up</li><li>Who handles replies, booking and handover today</li></ul><div id="calendar-embed" className="calendar-embed">{ready&&<iframe src={business.booking+'&embed_domain=automation.cyberworldgroups.com&embed_type=Inline'} title="Schedule a free blueprint call with Ayodele" loading="lazy"/>}</div><p className="mb-6 text-muted-foreground">If the calendar does not load, open it directly.</p><Blueprint/><div className="precall-form"><InquiryForm precall/></div></PageShell>}
