export interface ContentPageData {path:string;title:string;description:string;h1:string;intro:string;sections:{title:string;text:string}[];faq:[string,string][];article?:boolean}
const commonFaq:[string,string][]=[
 ['Do I need a GoHighLevel account?',"You need an account for the build, but you do not need one before we talk. If you already use GHL, I can review how your account is organized. If you do not, we discuss the subscription and setup you need. The free blueprint call does not include a software subscription. We agree on access and responsibilities before work starts."],
 ['How long does a typical build take?',"A typical build takes about 14 days once the scope, access and content are ready. A migration, several pipelines or custom integrations may need more time. I put the expected schedule in the written blueprint before you commit. We then test the system and walk your team through it. Timing is a planning estimate, not a promise of business results."],
 ['What does it cost?',"Starter is $1,500 one-time and includes CRM setup, one funnel, a basic email and SMS sequence and calendar integration. Growth is $3,000 one-time and adds more workflows, reputation management, two funnels and 30 days of optimization support. Enterprise is priced to the agreed scope. Software subscriptions, messaging usage and paid advertising are discussed separately; they are not the free call."],
 ['How do you handle consent and regional rules?',"We discuss where your contacts live, how they opted in and what channels they agreed to receive. Those details affect the workflow, not just the wording of a message. GDPR, CCPA, TCPA and CASL may be relevant depending on the audience and channel. I can help map consent and opt-out handling into the setup, but I do not replace your legal adviser."],
];
export const contentPages:ContentPageData[]=[
 {path:'/real-estate-automation',title:'Real Estate Automation | CyberWorld Automations',description:'GoHighLevel for real estate: organize property inquiries, showing requests and lead follow-up. Explore a practical CRM plan and book a free blueprint call.',h1:'GoHighLevel for real estate',intro:"I build GoHighLevel systems for real estate agents, brokerages and property managers who want a clear response to each inquiry. The work connects lead capture, follow-up, showing requests and handoffs. We start with your actual process, not a template that assumes every buyer and seller needs the same conversation.",sections:[
 {title:'When an inquiry arrives at the wrong moment',text:"It's 9pm. A new Zillow lead arrives while you are at your kid's game. By morning, the person may have contacted other agents. A useful first reply acknowledges the inquiry and explains what happens next. It does not pretend that you personally reviewed a property while you were away. I help separate that acknowledgment from the conversation an agent needs to have. The workflow records the source, assigns responsibility and makes the next task visible."},
 {title:'Build a pipeline around real decisions',text:"A buyer asking for a showing, a seller asking for a valuation and a tenant asking about availability need different next steps. I map those paths with your team before creating stages in the GHL CRM. A stage should describe something useful: inquiry received, contact attempted, conversation started or showing requested. It should not become a parking place for forgotten contacts. Clear ownership and a realistic next action matter more than a long list of automation triggers."},
 {title:'Follow up without pretending to be a person',text:"Your email and SMS messages should say who is contacting the lead and why. I write the sequence around the property inquiry and the permissions you actually have. We discuss what happens if someone replies, books, declines or asks not to hear from you. A reply should stop the inappropriate sequence and put the conversation in front of the right agent. Calendar reminders help with logistics; they should not replace answering a buyer's questions."},
 {title:'What I need from your brokerage',text:"Bring the sources of your inquiries, the calendar you use and a rough outline of who handles each lead. If you have an existing CRM, we review fields, tags and open opportunities before migrating anything. We also look at consent records and what your agents should be allowed to access. A smaller, clean import is often more useful than moving every old spreadsheet column without understanding it. The written blueprint lists the agreed sources, workflows and testing steps."},
 {title:'Where we work',text:"I work with real estate teams in the US, Canada and Europe. We can discuss time zones, team responsibilities and regional communication requirements without assuming that one message sequence works everywhere. GDPR, CCPA and TCPA may affect certain workflows; CASL matters for Canadian commercial messages. We plan around the consent your team has and ask you to review the legal basis with your adviser. No physical office is claimed on this site."}],faq:commonFaq},
 {path:'/home-services-automation',title:'Home Services Automation | CyberWorld Automations',description:'Connect missed calls, estimates, job reminders and review requests in GoHighLevel. See how home services automation works and book a free blueprint call.',h1:'Home services automation that follows the job',intro:"I build GHL systems for home service businesses that need a clear path from inquiry to estimate to scheduled work. Missed-call responses, reminders and follow-up can share one process. We agree on where automation helps and where a dispatcher, technician or owner should take over the conversation.",sections:[
 {title:'You are on a job when the phone rings',text:"The customer still needs help even when your hands are full. A missed-call text can acknowledge that you could not answer and invite them to share what they need. It should not claim you can attend immediately or give an estimate without context. I connect the response to a visible opportunity so the team can return the call. The aim is an organized handoff, not an automated promise your technician cannot keep."},
 {title:'Make the estimate a starting point, not the end',text:"Sending an estimate is not the same as closing the conversation. I help create a follow-up path that checks whether the customer has questions and offers the next practical step. The workflow needs to know when an estimate is accepted, declined or still waiting. If your team updates that status, the system can stop unnecessary reminders. We agree on timing and wording that fit your service instead of treating a roof replacement like a routine cleaning appointment."},
 {title:'Keep scheduling connected to the real calendar',text:"A calendar is useful only when its availability reflects your team's capacity. Travel time, job duration and the difference between an estimate visit and actual work all matter. I review how your business schedules before adding booking links. Confirmations can state what the customer needs to know and reminders can reduce avoidable confusion. If a job changes, someone still needs to update the schedule; automation should support that responsibility rather than hide it."},
 {title:'Ask for honest feedback after completed work',text:"Review requests belong after a genuine job or service interaction. I connect the completed status to a simple feedback request using the wording your business approves. The system should not invent ratings, publish quotes or suggest that every customer was happy. We also discuss how your team handles a complaint before it becomes another forgotten message. Seasonal follow-up can be useful, but it needs appropriate permission and should stop when someone opts out."},
 {title:'Where we work and what to bring',text:"I work with HVAC, plumbing, roofing, cleaning, landscaping and electrical businesses in the US, Canada and Europe. Bring your current phone setup, booking process, estimate method and a description of how jobs are marked complete. Regional consent and messaging requirements such as TCPA, CCPA, CASL and GDPR may affect the setup. Your written blueprint identifies the connections and responsibilities before we build. We do not claim local offices or guaranteed job numbers."}],faq:commonFaq},
 {path:'/coach-automation',title:'Coach Automation | CyberWorld Automations',description:'GoHighLevel for coaches: connect inquiries, webinar registration, sales calls and onboarding. Build clearer follow-up with a free automation blueprint call.',h1:'GoHighLevel for coaches and course creators',intro:"I connect the steps between an inquiry and a coaching conversation: registration, follow-up, call booking and onboarding. A GoHighLevel system can organize those handoffs without turning every interaction into a sales script. The blueprint starts with your offer and audience, so the messages have a reason to exist.",sections:[
 {title:'Your next client is waiting in an unread message',text:"You finish a coaching session and find inquiries in several places. Some people want a course link, others want to know if your coaching is right for them. I help bring those contacts into a clear process. An acknowledgment can tell someone what happens next while you are busy. The important part is what follows: the right information, a realistic invitation and a person who can answer a question that a workflow cannot."},
 {title:'A funnel should explain the actual offer',text:"Before building a landing page, I ask what you sell, who it is for and what the next step should be. A webinar registration, an application and a direct call booking are different actions. The page should not promise outcomes you have not established. I connect the form to the right tags and follow-up so someone does not receive a course pitch when they asked about private coaching. Clear routing is part of the offer, not just an administrative detail."},
 {title:'Registration needs a reliable next step',text:"A registration confirmation should contain the details the person needs: what they registered for and how to attend or continue. Reminder timing depends on your actual schedule. I review what happens after the event, including whether the person attended, requested more information or booked a call. We do not assume that everyone who registers is ready to buy. Replies, booking and opt-outs need to change the sequence so the system responds to the person's actions."},
 {title:'Onboarding starts after the agreement',text:"Your new client needs a clear introduction to your process, not another stream of prospect messages. I map what happens once your team confirms the client is ready for onboarding. That may include an intake form, scheduling information and check-in reminders. We discuss which details belong in the CRM and which should stay in a separate secure system. Coaching relationships can involve sensitive information; collecting more than the workflow needs makes the setup harder to manage."},
 {title:'Where we work and how we scope',text:"I work with business, fitness and life coaches, consultants and course creators in the US, Canada and Europe. Bring your offer, registration process, calendar and current client handoff. We review permission for email and SMS and discuss requirements such as GDPR, CASL, TCPA and CCPA where relevant. The written blueprint explains the agreed funnel, workflows and training. It does not guarantee clients, conversions or revenue, and software and messaging costs need their own review."}],faq:commonFaq},
 {path:'/ghl-crm-setup',title:'GHL CRM Setup | CyberWorld Automations',description:'Plan your GHL CRM setup and migration from spreadsheets or another platform. Organize fields, pipelines and follow-up with a free GoHighLevel blueprint call.',h1:'GHL CRM setup and migration',intro:"I set up GoHighLevel around the information your team actually uses: contacts, opportunities, ownership and next actions. A CRM migration is not just a file upload. We review what belongs in the new system, how consent is recorded and which workflows should start only after the data is checked.",sections:[
 {title:'Start with the decisions, then the fields',text:"A CRM should help someone decide what to do next. I ask your team which information is necessary to reply, qualify an inquiry or arrange an appointment. That usually gives us a shorter and more useful field list than copying every column from an old spreadsheet. We distinguish contact information from opportunity information and agree on labels that make sense to the people using the system. A field without a clear purpose can create extra work every time a lead arrives."},
 {title:'Clean the source before importing it',text:"Duplicate contacts, inconsistent phone formats and unclear consent records can become larger problems once workflows are active. We review the source data and identify what needs attention before import. I recommend keeping an original copy and agreeing on the mapping from old fields to new fields. The migration plan should explain how open opportunities are represented and how you will recognize a successful import. Old data should not automatically enroll people into a new marketing sequence."},
 {title:"Make pipelines reflect the team’s work",text:"Your pipeline is a shared picture of what has happened and what is still needed. I define stages with your team using actions they can recognize. We decide who owns an inquiry, what counts as a meaningful stage change and which reminders should be created from that change. Moving a card should not trigger a surprising message. The blueprint records the key triggers, conditions and stopping rules so testing can check behavior rather than just whether the screen looks tidy."},
 {title:'Test with sample contacts before launch',text:"I use clearly labeled sample data to check the intended paths before your team relies on them. We look at capture, assignment, calendar connections and what happens when someone replies or opts out. Testing also includes the ordinary mistakes: an incomplete form, a rescheduled appointment or an opportunity marked incorrectly. Your team needs to understand how to pause a workflow and correct a record. Handover includes a walkthrough, not simply a message saying the account is ready."},
 {title:'Keep access and regional requirements in view',text:"I work with real estate, home service and coaching teams in the US, Canada and Europe. We discuss who needs access, what information the workflow uses and how consent and opt-outs are stored. GDPR, CCPA, TCPA and CASL can affect the process depending on your contacts and channels. The free call helps scope the migration; your adviser should review legal obligations. Custom integrations and large migrations may require more time than a typical build, with scope agreed in writing."}],faq:commonFaq},
 {path:'/about',title:'About Us | CyberWorld Automations',description:'Meet CyberWorld Automations, a founder-led CyberWorld Groups company. Learn how Ayodele and the team plan GoHighLevel systems and work with your business.',h1:'About CyberWorld Automations',intro:"I'm Ayodele Ezekiel, founder of CyberWorld Automations, a CyberWorld Groups company. We build GoHighLevel systems for real estate teams, home service companies and online coaches. I lead the strategy and write the blueprint. You speak with me about your process before we agree on any paid work.",sections:[
 {title:'The follow-up problem we work on',text:"An inquiry can arrive while a business owner is busy doing the work they were hired to do. A real estate agent is at a showing, a technician is on a job and a coach is in a session. The problem is not always a lack of leads. Sometimes nobody knows who should reply or what happens after the first conversation. I build systems that make those responsibilities and next actions clear, without claiming that software can replace every human conversation."},
 {title:'The people behind CyberWorld',text:"I lead strategy and design your automation blueprint. Ahmed Akash, our Social Media Expert, handles social content and campaign assets. Sammy Ogundele, our Full Stack Developer, builds custom integrations and site features. Heather Fulmer, our Content Writer, writes the emails, SMS and funnel copy your leads read. Each role supports a different part of the customer journey. We only publish team photos and LinkedIn links when they have been provided; we do not use stock portraits as substitutes."},
 {title:'A written plan before a build',text:"The free call is a 30-minute conversation about your current tools, your audience and the place where follow-up breaks down. I then prepare a written blueprint before you commit to the build. That plan sets out the proposed CRM, funnels and workflows so you can understand what is included. It also identifies tasks that still belong to your team. A useful plan is specific enough to discuss, question and test, rather than a vague promise that automation will solve everything."},
 {title:'How we communicate during the work',text:"You can expect replies within one business day, a short video update each week and one point of contact. A typical build takes about 14 days after the scope, access and content are ready. We walk through the system and train your team at handover. Growth includes 30 days of optimization support; Enterprise includes 60 days. Starter does not include the extended optimization period. Custom work is scoped separately so a larger integration does not get hidden inside a smaller plan."},
 {title:'Where we work and what we do not claim',text:"We serve the US, Canada and Europe. We do not claim a physical office where no address has been provided, publish invented client results or use fake reviews to make the company look larger. Example dashboards on this site use sample data and are labeled accordingly. We discuss regional communication requirements such as GDPR, CCPA, TCPA and CASL as part of workflow planning, not as a legal certification. For the wider company, you can visit CyberWorld Groups at cyberworldgroups.com."}],faq:commonFaq},
];
export const generalFaq:[string,string][]=[['What is GoHighLevel?',"GoHighLevel is a platform that brings CRM contacts, opportunities, funnels, forms, calendars, email, SMS and workflows into one account. I use it to connect the steps in your lead process. Buying the platform alone does not decide how your team should work. The blueprint maps those decisions so the tools have a purpose, including who replies and when a sequence should stop."],...commonFaq.slice(0,3),['Do you offer ongoing support?',"Growth includes 30 days of optimization support, and Enterprise includes 60 days with a dedicated account manager. Starter covers the initial setup and handover but does not include an extended optimization period. We can discuss longer-term support needs during the call. I do not publish an ongoing contract length or payment policy that has not been agreed; any further work needs a clear scope."],['Can I upgrade later?',"Yes, we can scope additional funnels, workflows or integrations as your business needs change. We review your existing setup before adding another layer, so the upgrade supports a real process rather than duplicating it. An upgrade is not an automatic commitment or a promise that every feature fits the original price. You see the proposed work and agree on it before we change the system."],['How is this different from a marketing agency?',"Our focus is how your business handles inquiries and follow-up inside GoHighLevel. That can involve funnel pages and messaging, but it is not the same as running every part of a marketing campaign. We start with the leads, offers and team responsibilities you already have. Automation cannot guarantee demand. If paid advertising or other campaign work is needed, it must be discussed and scoped separately."],['Which industries do you serve?',"We specialize in real estate, home services and online coaches and course creators across the US, Canada and Europe. Each has different scheduling, handoff and messaging needs, so I do not assume that one generic sequence works for all of them. The call is a chance to explain your process and check fit. We do not claim physical offices or local certifications that have not been supplied."]];
