import { Header, Footer } from './website';
import { Blueprint } from './shared';
import { StructuredData } from './structured-data';
import { business, siteConfig } from '@/config/siteConfig';
import { TeamSection } from './trust';
import type { ContentPageData } from './content';
export const relatedLinks=[['/real-estate-automation','GoHighLevel for real estate'],['/home-services-automation','Home services automation'],['/coach-automation','GoHighLevel for coaches'],['/ghl-crm-setup','GHL CRM setup and migration'],['/about','About our team'],['/faq','Automation questions'],['/blog','Practical automation articles'],['/book','Prepare for a blueprint call'],['/results','Proof and example systems']];
export function PageShell({title,children}:{title:string;children:React.ReactNode}){return <><Header/><main className="inner-page content-width"><nav className="breadcrumbs" aria-label="Breadcrumb"><a href="/">Home</a><span aria-hidden="true">/</span><span>{title}</span></nav>{children}</main><Footer/></>}
export function ContentPage({page}:{page:ContentPageData}){return <PageShell title={page.h1}><StructuredData path={page.path} title={page.h1} faq={page.faq}/><article className="article-body"><p className="eyebrow">{page.article?'BY AYODELE EZEKIEL':'CYBERWORLD AUTOMATIONS'}</p><h1>{page.h1}</h1><p className="answer-first">{page.intro}</p>{page.article&&<div className="author-line">{siteConfig.founderPhoto&&<img src={siteConfig.founderPhoto} width={64} height={64} alt="Ayodele Ezekiel, Founder at CyberWorld Automations"/>}<p><b>Ayodele Ezekiel</b><br/>Founder. I lead strategy and design your GoHighLevel automation blueprint.</p></div>}<p className="updated">Last updated: 6 October 2026</p>{page.sections.map(s=><section key={s.title}><h2>{s.title}</h2><p>{s.text}</p></section>)}{page.path==='/about'&&<><TeamSection/><a href={business.parentUrl} target="_blank" rel="noopener noreferrer">Meet the wider CyberWorld Groups team</a></>}<section className="content-faq"><h2>Questions about {page.article?'this process':'the build'}</h2>{page.faq.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</section><section><h2>Related services</h2><nav className="related-links">{relatedLinks.filter(([path])=>path!==page.path).map(([path,label])=><a href={path} key={path}>{label}</a>)}</nav></section><div className="article-cta"><h2>Let's map your next step</h2><Blueprint/></div></article></PageShell>}
