import { useState, type FormEvent } from 'react';
import { Button } from '@/components/ui/button';
import { submitInquiry } from '@/lib/inquiries.functions';
import { inquirySchema } from '@/lib/inquiry-schema';
import { trackEvent } from '@/lib/tracking';
export function InquiryForm({precall=false}:{precall?:boolean}){
 const [status,setStatus]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const node=e.currentTarget;const f=new FormData(node);const data=inquirySchema.safeParse({name:f.get('name'),email:f.get('email'),phone:String(f.get('phone')??''),industry:f.get('industry'),message:f.get('message'),kind:precall?'precall':'contact',crm:String(f.get('crm')??''),consent:f.get('consent')==='on',website:String(f.get('website')??'')});if(!data.success){setError('Please fill in the required fields and agree to be contacted.');return;}setBusy(true);setError('');try{await submitInquiry({data:data.data});trackEvent('form_submit');setStatus(precall?'Your pre-call notes have been saved for the team.':'Your message has been saved for the CyberWorld team.');node.reset();}catch(err){setError(err instanceof Error?err.message:'Your message could not be saved. Please try again or email us directly.');}finally{setBusy(false);}}
 return <form onSubmit={submit} className="contact-form"><h3>{precall?'A few notes before we talk':'Prefer to send a message?'}</h3><div className="grid gap-5 sm:grid-cols-2"><label>Full Name<input name="name" required maxLength={120} autoComplete="name" placeholder="Your full name"/></label><label>Email Address<input name="email" type="email" required maxLength={254} autoComplete="email" placeholder="you@company.com"/></label>{!precall&&<label>Phone Number<input name="phone" type="tel" required autoComplete="tel" pattern={'[\\d\\s\\+\\(\\)\\.\\-]{7,25}'} maxLength={25} placeholder="Your phone number"/></label>}<label>Industry<select name="industry" required defaultValue=""><option value="" disabled>Select your industry</option><option>Real Estate</option><option>Home Services</option><option>Online Coaching</option><option>Other</option></select></label>{precall&&<label>Current CRM<input name="crm" maxLength={120} placeholder="GoHighLevel, spreadsheets, or none"/></label>}</div><label className="mt-5 block">{precall?'Biggest lead problem':'Message'}<textarea name="message" rows={4} required maxLength={4000} placeholder="Tell Ayodele where your follow-up gets stuck."/></label><input name="website" tabIndex={-1} aria-hidden="true" className="hidden" autoComplete="off"/><label className="consent-line"><input type="checkbox" name="consent" required/><span>By submitting, you agree to be contacted about our services. See our <a href="/privacy">Privacy Policy</a>.</span></label><Button type="submit" className="blueprint mt-5 w-full" disabled={busy}>{busy?'Saving…':precall?'Send pre-call notes':'Send Us a Message'}</Button>{status&&<p role="status" className="mt-4 text-sm text-success">{status}</p>}{error&&<p role="alert" className="mt-4 text-sm text-destructive">{error}</p>}</form>;
}
