import { Linkedin, Phone, Mail, MessageCircle } from 'lucide-react';
import { business, siteConfig, team, type CaseStudy } from '@/config/siteConfig';
import { Blueprint, Heading, Section } from './shared';
import { trackEvent } from '@/lib/tracking';
export function TeamSection(){
 const members=team.filter(p=>p.role==='Founder'?siteConfig.founderPhoto:siteConfig.teamPhotos?.[p.name]);
 if(!members.length)return null;
 return <Section><Heading eyebrow="OUR TEAM" title="The people behind CyberWorld"/><div className="team-grid">{members.map(p=><article className={`service-card ${p.role==='Founder'?'founder-card':''}`} key={p.name}><img src={p.role==='Founder'?siteConfig.founderPhoto:siteConfig.teamPhotos?.[p.name]} alt={`${p.name}, ${p.role} at CyberWorld Automations`} width={480} height={480} loading="lazy" className="team-photo"/><h3>{p.name}</h3><p className="text-primary">{p.role}</p><p>{p.description}</p>{siteConfig.linkedinUrls?.[p.name]&&<a href={siteConfig.linkedinUrls[p.name]} target="_blank" rel="noopener noreferrer" aria-label={`${p.name} on LinkedIn`}><Linkedin/></a>}</article>)}</div><a className="text-primary" href={business.parentUrl} target="_blank" rel="noopener noreferrer">Meet the full CyberWorld Groups team</a></Section>;
}
export function FounderIntro(){
 if(!siteConfig.founderPhoto)return null;
 return <Section><div className="industry-panel"><img src={siteConfig.founderPhoto} width={600} height={600} loading="lazy" className="team-photo" alt="Ayodele Ezekiel, Founder at CyberWorld Automations"/><div><h2>Meet Ayodele</h2><p>I'm Ayodele, founder of CyberWorld Automations. I build GoHighLevel systems for real estate teams, home service companies and online coaches. Most businesses don't have a lead problem, they have a follow-up problem: leads come in, nobody replies fast enough, and the lead goes elsewhere. I set up systems that reply in seconds, book the appointment and keep following up. Every project starts with a free call and a written blueprint, so you see the plan before you pay.</p><Blueprint/></div></div><FounderVideo/></Section>;
}
export function FounderVideo(){
 // Native video needs a real caption file; hide inaccessible media until one is supplied.
 if(!siteConfig.videoUrl || !siteConfig.videoCaptions)return null;
 return <figure className="founder-video"><video controls preload="none" poster={siteConfig.videoThumbnail} onPlay={()=>trackEvent('video_play')}><source src={siteConfig.videoUrl}/><track kind="captions" src={siteConfig.videoCaptions} srcLang="en" label="English" default/></video>{siteConfig.isAIVideo&&<figcaption>AI-assisted video of Ayodele, reading his own script.</figcaption>}</figure>;
}
export function Credibility(){return <Section className="alternate"><div className="credibility-row"><div>{siteConfig.certificateVerifyUrl?<a className="text-primary" href={siteConfig.certificateVerifyUrl} target="_blank" rel="noopener noreferrer">{siteConfig.certificateImage&&<img src={siteConfig.certificateImage} alt="GoHighLevel Expert Certification for Ayodele Ezekiel, issued 23 July 2025" width={600} height={420} loading="lazy"/>}GoHighLevel Expert Certified (2025) · Verify credential</a>:<h3>GoHighLevel specialists</h3>}</div><div><h3>Tools we work with</h3><p>GoHighLevel · Zapier · Twilio · Stripe · Meta Ads · Zillow · Calendly · WhatsApp</p></div></div><div className="direct-contact"><a href={`mailto:${business.email}`}><Mail size={16}/>{business.email}</a><a href={`tel:${business.telephone}`}><Phone size={16}/>{business.phone}</a><a href={business.whatsapp} target="_blank" rel="noopener noreferrer"><MessageCircle size={16}/>WhatsApp</a></div><p className="text-center text-sm text-muted-foreground">Typical reply time: within one business day</p></Section>}
export function CaseStudyCard({study}:{study:CaseStudy}){if(!study.permission)return null;return <article className="service-card"><h3>{study.who}</h3><h4>Problem</h4><p>{study.problem}</p><h4>What we built</h4><p>{study.built}</p><h4>Result · {study.period}</h4><p>{study.result}</p>{study.photo&&<img src={study.photo} alt={study.who} width={600} height={400} loading="lazy"/>}{study.quote&&<blockquote>{study.quote}</blockquote>}<p className="text-sm text-muted-foreground">Shared with permission</p></article>}
export function Proof(){
 const stats=siteConfig.ownSystemStats;const complete=stats?.period && stats.leads && stats.firstResponseTime && stats.appointments;const studies=(siteConfig.realCaseStudies??[]).filter(s=>s.permission);
 return <Section><Heading eyebrow="PROOF, WITH CONTEXT" title="Results we can share"/>{complete&&<><h3>How CyberWorld Groups runs its own follow-up</h3><p>Our own system, not a client. Period: {stats.period}</p><dl className="stats-grid"><div><dt>Leads</dt><dd>{stats.leads}</dd></div><div><dt>First response time</dt><dd>{stats.firstResponseTime}</dd></div><div><dt>Appointments</dt><dd>{stats.appointments}</dd></div></dl></>}{studies.length>0&&<div className="grid gap-6 md:grid-cols-2">{studies.map(s=><CaseStudyCard study={s} key={s.who}/>)}</div>}{!complete&&!studies.length&&<div className="text-center"><p className="mx-auto mb-6 max-w-2xl text-muted-foreground">Be one of our first case studies. We're taking on a limited number of founding clients at a discounted rate. In exchange, we document your results with your permission.</p><Blueprint>Claim a founding client spot</Blueprint></div>}{(siteConfig.realTestimonials??[]).filter(t=>t.permission).map(t=><blockquote className="testimonial-card" key={t.name}><p>“{t.quote}”</p><cite>{t.name} · {t.role}</cite></blockquote>)}</Section>;
}
export function Fit(){return <Section className="alternate"><Heading eyebrow="LET'S BE CLEAR" title="Who this is for, and who it isn't"/><div className="grid gap-8 md:grid-cols-2"><div><h3>A good fit</h3><p>You already get leads. You want faster replies, clearer follow-up and a system your team can actually use.</p><h3>What the free call includes</h3><p>A 30-minute conversation with Ayodele about your industry, current CRM and where leads get stuck. A written blueprint comes before the paid build.</p></div><div><h3>Not a fit</h3><p>You have no lead flow yet, or you want guaranteed revenue, bookings or results. Automation helps manage opportunities; it doesn't create demand by itself.</p><h3>What it doesn't include</h3><p>The call is not a completed CRM, a paid advertising campaign or a guarantee. Implementation and software subscriptions are separate from the free conversation.</p></div></div></Section>}
export function ClearTerms(){const labels={dataOwnership:'Data ownership',contractLength:'Contract length',paymentTerms:'Payment terms',supportAfterBuild:'Support after the build',refundPolicy:'Refund policy'};const entries=Object.entries(siteConfig.terms??{}).filter(([,v])=>v);if(!entries.length)return null;return <aside className="clear-terms"><h3>Clear terms</h3><dl>{entries.map(([key,value])=><div key={key}><dt>{labels[key as keyof typeof labels]}</dt><dd>{value}</dd></div>)}</dl></aside>}
